smtp_on: true
smtp_host: email-smtp.eu-west-1.amazonaws.com
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: AKIAIVEK55CRNTOB2MQA
smtp_password: ArgkBoCt9PFv7Fxj2fgE+EevAfXrXcXPOLkCLTpnyQj7
smtp_from: no-reply@capdel.fr
smtp_fromname: ''
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
langcode: fr
