definitions:
  contact__site_page:
    weight: -49
    menu_name: footer
    parent: ''
    enabled: true
    expanded: false
  standard__front_page:
    weight: -9
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  user__page:
    weight: -47
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
  user__logout:
    weight: -48
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
  workbench__content:
    weight: -45
    menu_name: workbench
    parent: ''
    expanded: false
    enabled: false
  workbench__create_content:
    weight: -50
    menu_name: workbench
    parent: ''
    expanded: false
    enabled: true
  workbench__my_edited:
    weight: -48
    menu_name: workbench
    parent: ''
    enabled: false
    expanded: false
  workbench__all_content:
    weight: -49
    menu_name: workbench
    parent: ''
    expanded: false
    enabled: true
  workbench__configure:
    weight: -44
    menu_name: workbench
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
langcode: fr
