include_home_segment: true
home_segment_title: Accueil
home_segment_keep: 0
include_title_segment: true
language_path_prefix_as_segment: false
use_menu_title_as_fallback: false
remove_repeated_segments: true
absolute_paths: false
_core:
  default_config_hash: 5F17n6TxNfWQr_ApjgpZLd7MnBepM_yEG1SJw5ickg8
langcode: fr
include_invalid_paths: false
excluded_paths: ''
replaced_titles: 'Search::Recherche'
segments_separator: null
title_segment_as_link: false
title_from_page_when_available: false
hide_single_home_item: false
