cookie_lifetime: 100
domain: ''
domains_option: 1
domains_list: ''
eu_only: null
eu_only_js: null
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
exclude_admin_theme: false
langcode: fr
popup_agreed:
  value: '<h2>Thank you for accepting cookies</h2><p>You can now hide this message or find out more about cookies.</p>'
  format: restricted_html
popup_agree_button_message: 'J''accepte'
popup_agreed_enabled: false
popup_bg_hex: '181716'
popup_clicking_confirmation: false
popup_scrolling_confirmation: false
popup_delay: 1000
show_disagree_button: true
popup_disagree_button_message: 'En savoir plus '
popup_enabled: true
popup_find_more_button_message: 'More info'
popup_height: null
popup_hide_agreed: false
popup_hide_button_message: Hide
popup_info:
  value: '<h2>Ce site utilise des cookies à des fins de statistique d’audience, d’identification et d’analyse de vos centres d’intérêts, ou permettre d''enrichir notre contenu.</h2><p>Vous acceptez les cookies en cliquant sur le bouton "J''accepte"</p>'
  format: restricted_html
mobile_popup_info:
  value: ''
  format: full_html
mobile_breakpoint: 768
popup_link: /notice
popup_link_new_window: true
popup_position: false
fixed_top_position: true
popup_text_hex: ffffff
popup_width: 100%
use_bare_css: false
disagree_do_not_show_popup: false
reload_page: false
cookie_name: ''
exclude_uid_1: false
better_support_for_screen_readers: false
use_mobile_message: false
method: default
disagree_button_label: 'No, thanks'
disabled_javascripts: ''
whitelisted_cookies: ''
consent_storage_method: do_not_store
withdraw_message:
  value: '<h2>We use cookies on this site to enhance your user experience</h2><p>You have given your consent for us to set cookies.</p>'
  format: restricted_html
withdraw_action_button_label: 'Withdraw consent'
withdraw_tab_button_label: 'Privacy settings'
withdraw_enabled: false
_core:
  default_config_hash: m9leru0wVmD_yCnIJzIkZ9YhvEp3luuqLEx5Sr9CmRk
cookie_session: 0
popup_info_template: new
