display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        title:
          label: Titre
          separator: ', '
        type:
          label: Type
          separator: ', '
        status:
          label: Publié
          separator: ', '
        name:
          label: Auteur
          separator: ', '
        changed:
          label: 'Dernière mise à jour'
          separator: ', '
        edit_node:
          label: Actions
          text: modifier
      filters:
        title:
          expose:
            label: Titre
        type:
          expose:
            label: Type
        status:
          expose:
            label: Publié
      empty:
        area:
          content:
            value: 'Aucun contenu n''est disponible à l''édition pour vous.'
      use_more_text: 'voir tout'
  block_1:
    display_options:
      pager:
        options:
          tags:
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      filters:
        status:
          expose:
            label: Publié
      fields:
        title:
          label: Titre
          separator: ', '
        type:
          label: Type
          separator: ', '
        name:
          label: Auteur
          separator: ', '
        changed:
          label: 'Dernière mise à jour'
          separator: ', '
        edit_node:
          label: Actions
          text: modifier
